/**
 * Словарь «ключевое слово → категория» (ТЗ §2 п.3). Без модели: это таблица,
 * которую человек может прочитать и поправить, а не догадка, которую нельзя
 * проверить.
 *
 * Обе стороны сравнения проходят через `fold()` — приведение к верхнему
 * регистру плюс транслитерация. Поэтому «Пятёрочка» и «PYATEROCHKA» здесь одно
 * слово, и дублировать написания больше не нужно.
 *
 * Чего в этом словаре нет и быть не должно: слов про переводы, снятие наличных,
 * кэшбэк и комиссии. Их определяет `operation.ts` по служебному началу описания,
 * и делает это точнее. Раньше они жили здесь — и слово «ТЕЛЕФОН» из «Связи»
 * ловило «внешний перевод по номеру телефона»: сорок шесть операций и четверть
 * годовых трат уходили не в ту категорию, выглядя при этом правдоподобно.
 */
import type { Category } from './model.js'
import { foldKeyword } from './text.js'

/** Правило: категория и слова, по которым она узнаётся. */
export interface Rule {
  category: Category
  keywords: readonly string[]
}

export const RULES: readonly Rule[] = [
  {
    category: 'Продукты',
    keywords: [
      'ПЯТЕРОЧКА',
      'PYATEROCHKA',
      'PEREKRESTOK',
      'ПЕРЕКРЕСТОК',
      'МАГНИТ',
      'MAGNIT',
      'ЛЕНТА',
      'LENTA',
      'АШАН',
      'AUCHAN',
      'ДИКСИ',
      'DIXY',
      'ВКУСВИЛЛ',
      'VKUSVILL',
      'АЗБУКА ВКУСА',
      'AZBUKA',
      'МЕТРО',
      'METRO C',
      'OKEY',
      'ОКЕЙ',
      'SPAR',
      'СПАР',
      'ВЕРНЫЙ',
      'VERNYI',
      'SAMOKAT',
      'САМОКАТ',
      'ЯНДЕКС ЛАВКА',
      'YANDEX LAVKA',
      'LAVKA',
      'GLOBUS',
      'ГЛОБУС',
      'МИРАТОРГ',
      'MIRATORG',
      'ПРОДУКТЫ',
      'SUPERMARKET',
      'ГРОЗЕРИ',
      'GROCERY',
      'ФЕРМА',
      'ПЕКАРНЯ',
      'BAKERY',
      'МЯСНОВ',
      'ЯРЧЕ',
      'MAGNOLIYA',
      'AZBUKAVKUSA',
      'SUXOFRUCT',
      'SUKHOFRUKT',
      'PTITSA SINITSA',
      'MOYCHAY',
      'LAVKA PEKARYA',
      'BULOCHNAYA',
      'GASTRONOM',
      'SKLADOCHNAYA',
      'VV ',
      'PETROVSKIY',
      'ПЕТРОВСКИЙ',
      'KRASNYJ RAK',
      'VERNYJ',
    ],
  },
  {
    category: 'Кафе и рестораны',
    keywords: [
      'КАФЕ',
      'CAFE',
      'КОФЕ',
      'COFFEE',
      'РЕСТОРАН',
      'RESTAURANT',
      'БАР ',
      'PUB',
      'ШОКОЛАДНИЦА',
      'SHOKOLADNITSA',
      'СТАРБАКС',
      'STARBUCKS',
      'КОФЕМАНИЯ',
      'СУРФ КОФЕ',
      'SURF COFFEE',
      // Терминал пишет имя слитно: «SURFCOFFEE», «DRINKITMOSKVA». Слово с
      // пробелом через это не перескакивает.
      'SURFCOFFEE',
      'ДРИНКИТ',
      'DRINKIT',
      'КОРЧМА',
      'KORCHMA',
      'FASTFOOD',
      'ФАСТФУД',
      'ONE PRICE COFFEE',
      'СКУРАТОВ',
      'DOUBLE B',
      'МАКДОНАЛДС',
      'MCDONALD',
      'ВКУСНО И ТОЧКА',
      'VKUSNO',
      'БУРГЕР',
      'BURGER',
      'KFC',
      'РОСТИКС',
      'ROSTIC',
      'ДОДО',
      'DODO',
      'ПИЦЦА',
      'PIZZA',
      'СУШИ',
      'SUSHI',
      'ЯНДЕКС ЕДА',
      'YANDEX EDA',
      'DELIVERY CLUB',
      'DELIVERY',
      'КУХНЯ НА РАЙОНЕ',
      'ТЕРЕМОК',
      'TEREMOK',
      'ЁЛКИ ПАЛКИ',
      'ТАНУКИ',
      'TANUKI',
      'ХЛЕБ НАСУЩНЫЙ',
      'СТОЛОВАЯ',
      'БУФЕТ',
      'ШАУРМА',
      'DONER',
      'ЧАЙХОНА',
      'ПАБ',
      'BISTRO',
      'БИСТРО',
      'KOFEJNYA',
      'KOFEYNYA',
      'DUSHA LAVASHA',
      'BRATYA KARAVAEVY',
      'KARAVAEV',
      'CHOPCHOP',
      'KHINKALI',
      'OBED ',
      'QSR',
      'STOLOVAYA',
      'FOODBAND',
      'KOMMUNA LAB',
      'PROSVET',
    ],
  },
  {
    category: 'Транспорт',
    keywords: [
      'МЕТРО ',
      'METROPOLITEN',
      'МЕТРОПОЛИТЕН',
      'ТРОЙКА',
      'TROIKA',
      'ПОДОРОЖНИК',
      'МОСГОРТРАНС',
      'MOSGORTRANS',
      'ГОРТРАНС',
      'АВТОБУС',
      'ТРАМВАЙ',
      'ТРОЛЛЕЙБУС',
      'РЖД',
      'RZD',
      'ТУТУ',
      'TUTU',
      'АЭРОЭКСПРЕСС',
      'AEROEXPRESS',
      'ЦППК',
      'ЭЛЕКТРИЧК',
      'ТРАНСПОРТ',
      'TRANSPORT',
      'КАРШЕРИНГ',
      'ДЕЛИМОБИЛЬ',
      'DELIMOBIL',
      'ЯНДЕКС ДРАЙВ',
      'YANDEX DRIVE',
      'CITYDRIVE',
      'BELKACAR',
      'САМОКАТЫ',
      'WHOOSH',
      'ЮРЕНТ',
      'URENT',
      'SCOOTER',
      'RUSSIAN RAILWAYS',
      'ЛАСТОЧКА',
      'SAMOKAT SHERING',
    ],
  },
  {
    category: 'Такси',
    keywords: [
      'ТАКСИ',
      'TAXI',
      'ЯНДЕКС ГО',
      'YANDEX GO',
      'YANDEX TAXI',
      'UBER',
      'CITYMOBIL',
      'СИТИМОБИЛ',
      'ВЕЗЕТ',
      'МАКСИМ',
      'MAXIM',
      'ДИДИ',
      'DIDI',
      'YANDEXGO',
      'YM GO',
      'YM YANDEX',
    ],
  },
  {
    category: 'Автомобиль',
    keywords: [
      'ЛУКОЙЛ',
      'LUKOIL',
      'ГАЗПРОМНЕФТЬ',
      'GAZPROMNEFT',
      'РОСНЕФТЬ',
      'ROSNEFT',
      'ТАТНЕФТЬ',
      'НЕФТЬ МАГИСТРАЛЬ',
      'АЗС',
      'ЗАПРАВК',
      'FUEL',
      'PETROL',
      'BENZIN',
      'ШИНОМОНТАЖ',
      'АВТОСЕРВИС',
      'АВТОМОЙКА',
      'МОЙКА',
      'АВТОЗАПЧАСТИ',
      'EXIST',
      'ЕМЕКС',
      'EMEX',
      'ПАРКОВК',
      'PARKING',
      'ПАРКИНГ',
      // Московский паркинг пишется слитно с ведомством: «AMPP-MOSPARKING».
      'MOSPARKING',
      'МОСПАРКИНГ',
      'ОСАГО',
      'КАСКО',
      'АВТОДОР',
      'ПЛАТОН',
      'ЗАПЧАСТИ',
      'TATNEFT',
      'AZS ',
      'AVTODOR',
      'NEFT ',
    ],
  },
  {
    category: 'Жильё и ЖКХ',
    keywords: [
      'ЖКХ',
      'КОММУНАЛ',
      'КВАРТПЛАТА',
      'ЕИРЦ',
      'ЕРЦ ',
      'МОСЭНЕРГОСБЫТ',
      'ЭНЕРГОСБЫТ',
      'МОСВОДОКАНАЛ',
      'ВОДОКАНАЛ',
      'ТЕПЛОСЕТ',
      'ГАЗПРОМ МЕЖРЕГИОНГАЗ',
      'ЭЛЕКТРОЭНЕРГ',
      'УПРАВЛЯЮЩАЯ КОМПАНИЯ',
      'ТСЖ',
      'АРЕНДА',
      'НАЕМ ЖИЛ',
      'КАПРЕМОНТ',
      'ДОМОФОН',
      'ИПОТЕК',
      'PLATIPOMIRU',
      'ЖКУ',
      'ЕПД',
      'КВАРТПЛАТ',
    ],
  },
  {
    category: 'Связь и подписки',
    keywords: [
      'МТС',
      'MTS',
      'БИЛАЙН',
      'BEELINE',
      'МЕГАФОН',
      'MEGAFON',
      'ТЕЛЕ2',
      'TELE2',
      'YOTA',
      'ЙОТА',
      'РОСТЕЛЕКОМ',
      'ROSTELECOM',
      'ДОМ РУ',
      'DOMRU',
      'ХОСТИНГ',
      'HOSTING',
      'REG RU',
      'TIMEWEB',
      'СВЯЗНОЙ',
      'AKADO',
      'ONLIME',
      'ЭР ТЕЛЕКОМ',
      'T2 MOBILE',
      'MBANK T2',
    ],
  },
  {
    category: 'Подписки',
    keywords: [
      'ЯНДЕКС ПЛЮС',
      'YANDEX PLUS',
      'PLUS MULTI',
      'КИНОПОИСК',
      'KINOPOISK',
      'ОККО',
      'OKKO',
      'IVI',
      'ИВИ',
      'WINK',
      'ПРЕМЬЕР',
      'PREMIER',
      'START RU',
      'СБЕР ПРАЙМ',
      'СБЕРПРАЙМ',
      'VK MUSIC',
      'VK COMBO',
      'ЯНДЕКС МУЗЫК',
      'SPOTIFY',
      'APPLE COM BILL',
      'ITUNES',
      'GOOGLE PLAY',
      'YOUTUBE PREMIUM',
      'NETFLIX',
      'ПОДПИСК',
      'SUBSCRIPTION',
      'ЛИТРЕС',
      'LITRES',
      'STORYTEL',
      'ЯНДЕКС 360',
      'DROPBOX',
      'ICLOUD',
      'NOTION',
      'FIGMA',
      'ADOBE',
    ],
  },
  {
    category: 'Здоровье',
    keywords: [
      'АПТЕК',
      'APTEK',
      'PHARM',
      'ФАРМ',
      'ЗДРАВСИТИ',
      'ГОРЗДРАВ',
      'РИГЛА',
      'RIGLA',
      'ОЗЕРКИ',
      'СТОМАТОЛОГ',
      'STOMATOLOG',
      'DENTAL',
      'КЛИНИК',
      'CLINIC',
      'МЕДИЦИН',
      'ПОЛИКЛИНИК',
      'ИНВИТРО',
      'INVITRO',
      'ГЕМОТЕСТ',
      'GEMOTEST',
      'СИТИЛАБ',
      'ЛАБОРАТОРИ',
      'АНАЛИЗ',
      'ВРАЧ',
      'ДОКТОР',
      'DOCTOR',
      'МЕДСИ',
      'MEDSI',
      'ОПТИК',
      'OPTIC',
      'ОЧКИ',
      'ДМС',
      'MSKAPT',
      'PROFMEDZDRAV',
      'APTEKA',
      'АПТЕЧН',
    ],
  },
  {
    category: 'Красота',
    keywords: [
      'ЛЭТУАЛЬ',
      'LETUAL',
      'ILE DE BEAUTE',
      'ЗОЛОТОЕ ЯБЛОКО',
      'GOLDAPPLE',
      'РИВ ГОШ',
      'RIVE GAUCHE',
      'ПОДРУЖКА',
      'МАГНИТ КОСМЕТИК',
      'ПАРИКМАХЕР',
      'BARBER',
      'БАРБЕР',
      'САЛОН КРАСОТЫ',
      'BEAUTY',
      'МАНИКЮР',
      'NAIL',
      'SPA ',
      'КОСМЕТИК',
      'COSMETIC',
    ],
  },
  {
    category: 'Одежда',
    keywords: [
      'ZARA',
      'ЗАРА',
      'UNIQLO',
      'HM COM',
      'H M ',
      'MASSIMO DUTTI',
      'BERSHKA',
      'PULL BEAR',
      'STRADIVARIUS',
      'GLORIA JEANS',
      'ГЛОРИЯ ДЖИНС',
      'ОСТИН',
      'OSTIN',
      'ZOLLA',
      'SELA',
      'LOVE REPUBLIC',
      'BEFREE',
      'СПОРТМАСТЕР',
      'SPORTMASTER',
      'DECATHLON',
      'ДЕКАТЛОН',
      'RENDEZ VOUS',
      'КАРИ',
      'KARI',
      'ECCO',
      'ОБУВЬ',
      'ОДЕЖД',
      'CLOTHING',
      'ХИМЧИСТК',
    ],
  },
  {
    category: 'Дом и техника',
    keywords: [
      'ИКЕА',
      'IKEA',
      'ЛЕРУА',
      'LEROY',
      'ОБИ',
      'OBI ',
      'ПЕТРОВИЧ',
      'СТРОЙ',
      'ХОФФ',
      'HOFF',
      'МВИДЕО',
      'M VIDEO',
      'ЭЛЬДОРАДО',
      'ELDORADO',
      'DNS ',
      'ДНС',
      'СИТИЛИНК',
      'CITILINK',
      'RE STORE',
      'RESTORE',
      'ФИКС ПРАЙС',
      'FIX PRICE',
      'ТЕХНИК',
      'МЕБЕЛЬ',
      'ПОСУД',
      'ХОЗТОВАР',
      'KHUDOZHESTVENNYE',
      'SMARTAUDIO',
      'STROYMATERIAL',
      'DEFAKTO',
      'BLASTBIT',
    ],
  },
  {
    category: 'Дети',
    keywords: [
      'ДЕТСКИЙ МИР',
      'DETMIR',
      'ДЕТМИР',
      'ДЕТСК',
      'ИГРУШК',
      'TOY',
      'КОРАБЛИК',
      'МАМА',
      'ДЕТСАД',
      'ШКОЛА ПИТАНИ',
      'ПОДГУЗНИК',
      'HAPPYLON',
      'КИДБУРГ',
    ],
  },
  {
    category: 'Питомцы',
    keywords: [
      'ЗООМАГАЗИН',
      'ЗООТОВАР',
      'ЗООВЕТ',
      'ВЕТЕРИНАР',
      'ВЕТКЛИНИК',
      'ЧЕТЫРЕ ЛАПЫ',
      'ЗООПЛАНЕТА',
      'PETSHOP',
      'PET SHOP',
      'ЗООЭКСПРЕСС',
      'КОРМ ДЛЯ',
    ],
  },
  {
    category: 'Развлечения',
    keywords: [
      'КИНО',
      'CINEMA',
      'КИНОТЕАТР',
      'КАРО',
      'ФОРМУЛА КИНО',
      'ТЕАТР',
      'THEATRE',
      'КОНЦЕРТ',
      'CONCERT',
      'МУЗЕЙ',
      'MUSEUM',
      'ВЫСТАВК',
      'БИЛЕТ',
      'TICKET',
      'МУЗЕЙ',
      'MUZEJ',
      'MUSEUM',
      'МОСБИЛЕТ',
      'MOSBILET',
      'ЯНДЕКС АФИША',
      'AFISHA',
      'КАССИР РУ',
      'PONYSHOW',
      'БОУЛИНГ',
      'КВЕСТ',
      'STEAM',
      'PLAYSTATION',
      'XBOX',
      'НАСТОЛЬН',
      'ФИТНЕС',
      'FITNESS',
      'СПОРТЗАЛ',
      'БАССЕЙН',
      'WORLD CLASS',
      'ALEX FITNESS',
      'ЙОГА',
      'TONN',
      'STANDUP',
      'КОМЕДИ',
      'ПОРЯДОК СЛОВ',
    ],
  },
  {
    category: 'Образование',
    keywords: [
      'КУРС',
      'COURSE',
      'ШКОЛА',
      'SCHOOL',
      'УНИВЕРСИТЕТ',
      'ИНСТИТУТ',
      'ОБУЧЕНИ',
      'SKILLBOX',
      'СКИЛБОКС',
      'НЕТОЛОГИЯ',
      'NETOLOGY',
      'ЯНДЕКС ПРАКТИКУМ',
      'PRACTICUM',
      'GEEKBRAINS',
      'СТЕПИК',
      'STEPIK',
      'COURSERA',
      'УЧЕБНИК',
      'РЕПЕТИТОР',
      'КНИГ',
      'ЧИТАЙ ГОРОД',
      'БУКВОЕД',
      'ЛАБИРИНТ',
    ],
  },
  {
    category: 'Путешествия',
    keywords: [
      'АЭРОФЛОТ',
      'AEROFLOT',
      'ПОБЕДА',
      'POBEDA',
      'S7 ',
      'УРАЛЬСКИЕ АВИАЛИНИИ',
      'АВИА',
      'AVIA',
      'AIRLINES',
      'AIRPORT',
      'АЭРОПОРТ',
      'ОТЕЛЬ',
      'HOTEL',
      'ХОСТЕЛ',
      'HOSTEL',
      'БРОНИР',
      'BOOKING',
      'ОСТРОВОК',
      'OSTROVOK',
      'СУТОЧНО',
      'YANDEX PUTESHESTVIYA',
      'ПУТЕШЕСТВИ',
      'ТУРАГЕНТ',
      'ТУРОПЕРАТОР',
      'AVIASALES',
      'YANDEX TRAVEL',
      'TUTU RU',
      'AVIASEILS',
      'АВИАСЕЙЛС',
      'OSTROVOK RU',
      'YANDEX AFISHA TRAVEL',
    ],
  },
  {
    category: 'Подарки',
    keywords: [
      'ПОДАРОК',
      'ПОДАРК',
      'GIFT',
      'ЦВЕТЫ',
      'FLOWER',
      'ЦВЕТОЧН',
      'БУКЕТ',
      'FLOWWOW',
      'TSVETY',
      'NOVYE TSVETY',
    ],
  },
  {
    category: 'Маркетплейсы',
    keywords: [
      'OZON',
      'ОЗОН',
      'WILDBERRIES',
      'ВАЙЛДБЕРРИЗ',
      'WB RU',
      'YM MARKET YANDEX',
      'MARKET YANDEX',
      'ЯНДЕКС МАРКЕТ',
      'YANDEX MARKET',
      'MEGAMARKET',
      'МЕГАМАРКЕТ',
      'SBERMEGAMARKET',
      'ALIEXPRESS',
      'АЛИЭКСПРЕСС',
      'AVITO',
      'АВИТО',
      'LAMODA',
      'ЛАМОДА',
      'JOOM',
      'DETMIR RU',
    ],
  },
  {
    category: 'Алкоголь',
    keywords: [
      'AROMATNYJ MIR',
      'АРОМАТНЫЙ МИР',
      'WINELAB',
      'ВИНЛАБ',
      'КРАСНОЕ БЕЛОЕ',
      'KRASNOE BELOE',
      'БРИСТОЛЬ',
      'BRISTOL',
      'ВИНОТЕКА',
      'VINOTEKA',
      'WINESTYLE',
      'АЛКОТЕКА',
      'ALKOTEKA',
      'ВИНОЛАБ',
      'VINOLAB',
      'SIMPLE WINE',
      'ПИВОТЕКА',
    ],
  },
  {
    category: 'Переводы',
    keywords: [],
  },
  {
    category: 'Наличные',
    keywords: ['ATM'],
  },
  {
    category: 'Налоги и штрафы',
    keywords: [
      'НАЛОГ',
      'ФНС',
      'NALOG',
      'ШТРАФ',
      'ГИБДД',
      'GIBDD',
      'ГОСПОШЛИН',
      'ПОШЛИН',
      'ФССП',
      'СУДЕБН',
      'ГОСУСЛУГ',
    ],
  },
  {
    category: 'Кредиты',
    keywords: ['КРЕДИТ', 'CREDIT', 'ЗАЙМ', 'РАССРОЧК', 'ПРОЦЕНТЫ ПО'],
  },
  {
    category: 'Доход',
    keywords: ['ЗАРПЛАТ', 'ЗАРАБОТН', 'SALARY', 'АВАНС', 'ПРЕМИ', 'ГОНОРАР', 'ДИВИДЕНД'],
  },
]

/**
 * Короткое слово обязано совпадать целиком, длинное может совпасть началом.
 *
 * Причина в том, что короткое слово слишком легко оказывается началом чужого:
 * «AZS» ловил «AZSTROY», и строительный магазин становился заправкой. Длинному
 * слову («ПОДГУЗНИК») подстрочное совпадение, наоборот, нужно — оно ловит
 * падежи и множественное число.
 *
 * Граница — шесть букв. Пять оказалось мало: «МЕТРО» начинает «METROPOLIS», а
 * «ЛЕНТА» сидит внутри «VALENTA», и торговый центр с аптекой становились
 * продуктами. Всё, что короче шести, в русско-латинской мешанине выписки
 * слишком часто оказывается частью другого слова, поэтому совпадает целиком.
 *
 * Но и длинному слову подстрока нужна только справа. Слева слово обязано
 * начинаться с границы: без неё ровно пятибуквенные ключи ловили чужую
 * середину — «ЛЕНТА» внутри «VALENTA PHARM» делала аптеку продуктами, «МЕТРО»
 * внутри «METROPOLIS TRC» делала продуктами торговый центр. Тот же класс
 * ошибки, что с «AZSTROY», просто на пять букв дальше.
 *
 * Описание обрамлено пробелами в `normalize`, поэтому ведущий пробел в ключе —
 * это и есть «с начала слова», а отсутствие замыкающего оставляет падежи и
 * множественное число: « ПОДГУЗНИК» по-прежнему ловит «ПОДГУЗНИКИ».
 */
function indexKey(keyword: string): string {
  const folded = foldKeyword(keyword)
  const bare = folded.trim()
  if (bare.length >= 6 || bare.includes(' ')) return ` ${bare}`
  return ` ${bare} `
}

export const KEYWORD_INDEX: ReadonlyArray<readonly [string, Category]> = RULES.flatMap((rule) =>
  rule.keywords.map((keyword) => [indexKey(keyword), rule.category] as const),
).sort((a, b) => b[0].length - a[0].length)
